### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by richardkall** [foxyblocks/grunt-emblem#2]
Not working with jquery 2.0.2, latest emblem, ember 1.0.0-rc.6, handlebars 1.0.0-rc.4

**app/templates/application.emblem:**

```
h1 Title
linkTo "home" | Home
```

**Gruntfile:**

```
emblem:
  compile:
    files:
      '.tmp/javascripts/templates.js': ['app/templates/**/*.emblem']
    options:
      root: 'app/templates/'
      dependencies:
        jquery: 'app/vendor/jquery/jquery.js'
        ember: 'app/vendor/ember/ember.js'
        emblem: 'app/vendor/emblem/dist/emblem.js'
        handlebars: 'app/vendor/handlebars/handlebars.js'
```

I get this when running `grunt emblem --stack`:

``` bash
Running "emblem:compile" (emblem) task
Warning: Object #<Object> has no method 'replace' Use --force to continue.
TypeError: Object #<Object> has no method 'replace'
    at Object.JavaScriptCompiler.quotedString (<anonymous>:1996:8)
    at Object.JavaScriptCompiler.setupHelper (<anonymous>:2013:61)
    at Object.JavaScriptCompiler.invokeHelper (<anonymous>:1719:41)
    at Object.JavaScriptCompiler.compile (<anonymous>:1343:29)
    at Object.Ember.Handlebars.precompile (<anonymous>:19494:52)
    at Object.Emblem.precompile (<anonymous>:5805:28)
    at EmberBuilder.build (/Users/Richard/Sites/project/node_modules/grunt-emblem/tasks/emblem.js:144:37)
    at /Users/Richard/Sites/project/node_modules/grunt-emblem/tasks/emblem.js:67:42
    at Array.forEach (native)
    at /Users/Richard/Sites/project/node_modules/grunt-emblem/tasks/emblem.js:63:32
```
